/* LifeSim: content is data-first so new jobs, programs, items and events are easy to add. */
const JOBS = [
  { id:'cashier', path:'Retail', title:'Cashier', pay:1500, level:1, experience:0, education:'ged', skills:{}, previous:null },
  { id:'shift-lead', path:'Retail', title:'Shift Lead', pay:2300, level:2, experience:12, education:'ged', skills:{communication:15}, previous:'cashier' },
  { id:'assistant-manager', path:'Retail', title:'Assistant Manager', pay:3400, level:3, experience:24, education:'associate', skills:{business:25,communication:20}, previous:'shift-lead' },
  { id:'store-manager', path:'Retail', title:'Store Manager', pay:5200, level:4, experience:42, education:'associate', skills:{business:45,communication:35}, previous:'assistant-manager' },
  { id:'tech-support', path:'Technology', title:'Tech Support', pay:1900, level:1, experience:0, education:'ged', skills:{}, previous:null },
  { id:'junior-developer', path:'Technology', title:'Junior Developer', pay:3300, level:2, experience:12, education:'associate', skills:{technology:30}, previous:'tech-support' },
  { id:'software-developer', path:'Technology', title:'Software Developer', pay:6100, level:3, experience:24, education:'bachelor', skills:{technology:55,creativity:20}, previous:'junior-developer' },
  { id:'senior-developer', path:'Technology', title:'Senior Developer', pay:9800, level:4, experience:42, education:'bachelor', skills:{technology:75,creativity:35}, previous:'software-developer' },
  { id:'engineering-manager', path:'Technology', title:'Engineering Manager', pay:14500, level:5, experience:60, education:'master', skills:{technology:80,business:55,communication:55}, previous:'senior-developer' },
  { id:'medical-assistant', path:'Medical', title:'Medical Assistant', pay:2400, level:1, experience:0, education:'trade', skills:{medical:20,communication:10}, previous:null },
  { id:'nurse', path:'Medical', title:'Nurse', pay:4700, level:2, experience:18, education:'associate', skills:{medical:50,health:30}, previous:'medical-assistant' },
  { id:'physician-assistant', path:'Medical', title:'Physician Assistant', pay:8200, level:3, experience:36, education:'master', skills:{medical:70,communication:35}, previous:'nurse' },
  { id:'doctor', path:'Medical', title:'Doctor', pay:18000, level:4, experience:60, education:'professional', skills:{medical:90,health:50}, previous:'physician-assistant' },
  { id:'sales-associate', path:'Business', title:'Sales Associate', pay:2100, level:1, experience:0, education:'ged', skills:{}, previous:null },
  { id:'sales-manager', path:'Business', title:'Sales Manager', pay:4800, level:2, experience:18, education:'associate', skills:{business:35,communication:40}, previous:'sales-associate' },
  { id:'business-analyst', path:'Business', title:'Business Analyst', pay:7600, level:3, experience:30, education:'bachelor', skills:{business:60,technology:25}, previous:'sales-manager' },
  { id:'executive', path:'Business', title:'Executive', pay:17000, level:4, experience:60, education:'master', skills:{business:85,communication:65}, previous:'business-analyst' }
];
const EDUCATION = [
  {id:'ged',name:'High School / GED',cost:0,months:0,rank:0,unlocks:'Entry-level work'},
  {id:'trade',name:'Trade School',cost:2800,months:6,rank:1,unlocks:'Medical Assistant and practical skills'},
  {id:'associate',name:'Associate Degree',cost:6000,months:12,rank:2,unlocks:'Supervisory and technical careers'},
  {id:'bachelor',name:"Bachelor's Degree",cost:13000,months:24,rank:3,unlocks:'Professional careers'},
  {id:'master',name:"Master's Degree",cost:22000,months:18,rank:4,unlocks:'Leadership and specialist careers'},
  {id:'professional',name:'Professional Degree',cost:42000,months:36,rank:5,unlocks:'Doctor'}
];
const SKILLS = {technology:'Technology',business:'Business',communication:'Communication',fitness:'Fitness',creativity:'Creativity',mechanical:'Mechanical',medical:'Medical Knowledge'};
const HOUSING = [
  {id:'family',name:'Living with family',cost:0,expense:250,happiness:0,status:0}, {id:'shared',name:'Shared apartment',cost:1800,expense:650,happiness:5,status:1}, {id:'small-apartment',name:'Small apartment',cost:6500,expense:1100,happiness:12,status:2}, {id:'nice-apartment',name:'Nice apartment',cost:18000,expense:1800,happiness:20,status:3}, {id:'house',name:'House',cost:65000,expense:3000,happiness:32,status:5}, {id:'luxury-house',name:'Luxury house',cost:250000,expense:6500,happiness:45,status:10}
];
const PURCHASES = [
  {id:'phone',name:'A good phone',cost:700,description:'Stay connected and gain a little Social.',effect:{social:5}}, {id:'computer',name:'Computer',cost:1600,description:'Unlocks technology training and a small Technology boost.',effect:{technology:8},unlock:'technology'}, {id:'car',name:'Reliable car',cost:12000,description:'Unlocks better commutes and gives Career confidence.',effect:{career:4},unlock:'car'}, {id:'furniture',name:'Furniture set',cost:3500,description:'Makes home feel settled. Gain Happiness.',effect:{happiness:10}}, {id:'gaming',name:'Gaming setup',cost:2400,description:'A fun way to recover Energy and Happiness.',effect:{happiness:8},unlock:'gaming'}, {id:'clothes',name:'Nice clothes',cost:1200,description:'A little confidence goes a long way.',effect:{social:8,career:3}}, {id:'gym',name:'Gym membership',cost:900,description:'Unlocks stronger Fitness training.',effect:{fitness:5},unlock:'gym'}, {id:'vacation',name:'Vacation',cost:4500,description:'Take a real break. Gain Happiness and Social.',effect:{happiness:18,social:10}}
];
const EVENTS = [
  {title:'You are offered overtime.',text:'A busy month could accelerate your progress, but it will take a toll.',options:[{label:'Work overtime',hint:'+35% income, -12 Energy',effects:{money:'income35',energy:-12,experience:1}},{label:'Take the evening off',hint:'+8 Happiness, +8 Energy',effects:{happiness:8,energy:8}}]},
  {title:'A friend invites you out of town.',text:'You could make memories and meet new people, but the trip costs a little.',options:[{label:'Go on the trip',hint:'-$400, +15 Social, +10 Happiness',effects:{money:-400,social:15,happiness:10}},{label:'Stay home and save',hint:'+1 month of savings',effects:{money:250,happiness:-2}}]},
  {title:'A company offers a role in another city.',text:'The pay is better, but the move would raise your expenses.',options:[{label:'Accept the opportunity',hint:'+20% income, +10 Career, -$1,000',effects:{money:-1000,career:10,incomeBoost:.2}},{label:'Decline for now',hint:'+5 Happiness from stability',effects:{happiness:5}}]}
];
const DEFAULT_STATE = {version:2, ageMonths:216, money:250, jobId:null, experience:0, educationId:'ged', educationProgress:0, enrolledEducation:null, skills:{technology:0,business:0,communication:0,fitness:0,creativity:0,mechanical:0,medical:0}, happiness:65, energy:80, health:80, social:35, career:0, housingId:'family', purchases:[], milestones:[], log:[{age:216,text:'You started a new life with a little cash and plenty of choices.'}], actionCount:0, incomeBoost:0};
let state = loadState(); let pendingEvent = null; let toastTimer;
const $ = id => document.getElementById(id); const clamp=(n,min=0,max=100)=>Math.max(min,Math.min(max,n)); const money=n=>`$${Math.round(n).toLocaleString()}`; const job=()=>JOBS.find(x=>x.id===state.jobId); const housing=()=>HOUSING.find(x=>x.id===state.housingId)||HOUSING[0]; const education=()=>EDUCATION.find(x=>x.id===state.educationId)||EDUCATION[0];
function loadState(){ try { const saved=JSON.parse(localStorage.getItem('lifesim-save')); if(!saved) return structuredClone(DEFAULT_STATE); const s={...structuredClone(DEFAULT_STATE),...saved,skills:{...DEFAULT_STATE.skills,...(saved.skills||{})}}; if(!Array.isArray(s.purchases))s.purchases=[]; if(!Array.isArray(s.milestones))s.milestones=[]; if(!Array.isArray(s.log))s.log=[]; return s; } catch { return structuredClone(DEFAULT_STATE); } }
function save(){ localStorage.setItem('lifesim-save',JSON.stringify(state)); }
function ageText(){const y=Math.floor(state.ageMonths/12),m=Math.floor(state.ageMonths%12);return `${y}y ${m}m`;}
function stage(){const y=Math.floor(state.ageMonths/12);return y<25?'Young adult':y<40?'Building your life':y<60?'Established adult':'Seasoned professional';}
function notify(text){const t=$('toast');t.textContent=text;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2600);}
function log(text){state.log.unshift({age:state.ageMonths,text});state.log=state.log.slice(0,12);}
function addMilestone(id,title){if(state.milestones.some(x=>x.id===id))return;state.milestones.unshift({id,title,age:state.ageMonths});notify(`Milestone: ${title}`);}
function checkMilestones(){const j=job(); if(j)addMilestone('first-job','Got your first job'); if(state.housingId!=='family')addMilestone('first-home','Moved into your first apartment'); if(state.money>=10000)addMilestone('ten-k','Reached $10,000'); if(education().rank>=1)addMilestone('first-degree',`Completed ${education().name}`); if(j&&j.level>=2)addMilestone('promotion',`Promoted to ${j.title}`); if(state.purchases.includes('car'))addMilestone('car','Bought a car'); if(['house','luxury-house'].includes(state.housingId))addMilestone('house','Bought a house'); if(state.money>=1000000)addMilestone('millionaire','Reached $1,000,000'); if(j&&JOBS.filter(x=>x.path===j.path).every(x=>x.level>j.level||state.experience>=x.experience))addMilestone('top-career',`Reached the top of ${j.path}`);}
function advance(months,why){const h=housing(); const income=job()?.pay||0; state.ageMonths+=months; state.money+=income/12*months-h.expense/12*months; state.energy=clamp(state.energy-(months*3)); state.experience+=months*(job()?1:0); state.actionCount++; if(why)log(`${why} (${months} ${months===1?'month':'months'} passed).`); checkMilestones(); save(); render(); maybeEvent();}
function changeEffects(e){for(const [key,value] of Object.entries(e)){if(key==='money'){state.money+=typeof value==='number'?value:0;if(value==='income35')state.money+=(job()?.pay||0)/12*.35;}else if(key==='incomeBoost'){state.incomeBoost+=value;}else if(key==='experience'){state.experience+=value;}else if(key in state.skills)state.skills[key]=clamp(state.skills[key]+value);else if(key in state)state[key]=clamp(state[key]+value);}state.money=Math.max(0,state.money);}
function maybeEvent(){if(state.actionCount>0&&state.actionCount%4===0&&!pendingEvent){pendingEvent=EVENTS[Math.floor(Math.random()*EVENTS.length)];$('decision-title').textContent=pendingEvent.title;$('decision-text').textContent=pendingEvent.text;$('decision-options').innerHTML=pendingEvent.options.map((o,i)=>`<button data-event-option="${i}">${o.label}<span>${o.hint}</span></button>`).join('');$('decision-modal').classList.remove('hidden');}}
function requirements(j){const e=education();const reasons=[];if(e.rank<(EDUCATION.find(x=>x.id===j.education)?.rank||0))reasons.push(EDUCATION.find(x=>x.id===j.education).name);if(state.experience<j.experience)reasons.push(`${j.experience} months experience`);for(const [k,v] of Object.entries(j.skills))if((state.skills[k]||0)<v)reasons.push(`${SKILLS[k]} ${v}`);if(j.previous&&state.jobId!==j.previous)reasons.push(`previous: ${JOBS.find(x=>x.id===j.previous).title}`);return reasons;}
function doAction(action){const j=job();if(action==='work'){if(!j){notify('Choose an entry-level job first.');switchTab('career');return;}advance(1,`Worked a shift as ${j.title}`);state.skills.communication=clamp(state.skills.communication+(j.path==='Business'||j.path==='Retail'?1:0));}
else if(action==='work-batch'){if(!j){notify('Choose a job first.');switchTab('career');return;}advance(3,`Worked a three-month stretch as ${j.title}`);state.skills[j.path==='Technology'?'technology':j.path==='Medical'?'medical':j.path==='Business'?'business':'communication']=clamp((state.skills[j.path==='Technology'?'technology':j.path==='Medical'?'medical':j.path==='Business'?'business':'communication']||0)+3);}
else if(action==='study'){if(!state.enrolledEducation){notify('Choose a program in Education first.');switchTab('education-panel');return;}const ed=EDUCATION.find(x=>x.id===state.enrolledEducation);advance(1,'Studied for your program');state.educationProgress++;state.energy=clamp(state.energy-4);if(state.educationProgress>=ed.months){state.educationId=ed.id;state.enrolledEducation=null;state.educationProgress=0;log(`Completed ${ed.name}. New opportunities opened.`);notify(`${ed.name} completed!`);checkMilestones();save();render();}}
else if(action==='train'){const skill=actionDataSkill; if(!skill)return; if(state.money<40){notify('You need $40 for training.');return;}state.money-=40;advance(1,`Trained ${SKILLS[skill]}`);state.skills[skill]=clamp(state.skills[skill]+8);state.energy=clamp(state.energy-5);save();render();}
else if(action==='relax'){advance(.25,'Took time to relax');state.happiness=clamp(state.happiness+7);state.energy=clamp(state.energy+12);save();render();}
else if(action==='social'){advance(.25,'Spent time with friends');state.social=clamp(state.social+8);state.happiness=clamp(state.happiness+4);state.energy=clamp(state.energy-2);save();render();}
else if(action==='exercise'){advance(.25,'Exercised');state.skills.fitness=clamp(state.skills.fitness+5);state.health=clamp(state.health+2);state.energy=clamp(state.energy-7);save();render();}
}
let actionDataSkill=null;
function render(){const j=job(),h=housing(),ed=education();$('age').textContent=ageText();$('life-stage').textContent=stage();$('money').textContent=money(state.money);$('job').textContent=j?.title||'Unemployed';$('income').textContent=`${money((j?.pay||0)*(1+state.incomeBoost))} / month`;$('education').textContent=ed.name;$('housing').textContent=h.name;$('happiness').textContent=Math.round(state.happiness);$('energy').textContent=Math.round(state.energy);$('action-count').textContent=`${state.actionCount} actions`;
  $('life-actions').innerHTML=[['work','Work a shift',j?`Earn ${money(j.pay/12)} and gain experience`:'Get hired from Career'],['work-batch','Work 3 months',j?'Batch work and build your career':'Choose a job first'],['study','Study session',state.enrolledEducation?`${EDUCATION.find(x=>x.id===state.enrolledEducation).name}: ${state.educationProgress}/${EDUCATION.find(x=>x.id===state.enrolledEducation).months} months`:'Enroll in Education'],['relax','Relax','Recover Energy and gain Happiness'],['social','See friends','Build Social without using much time'],['exercise','Exercise','Improve Health and Fitness']].map(x=>`<button class="action-card" data-action="${x[0]}"><strong>${x[1]}</strong><small>${x[2]}</small></button>`).join('');
  $('activity-log').innerHTML=state.log.map(x=>`<div class="activity"><time>${Math.floor(x.age/12)}y ${x.age%12}m</time>${x.text}</div>`).join('')||'<div class="activity">Your timeline is ready for its first chapter.</div>';
  $('career-list').innerHTML=JOBS.map(x=>{const req=requirements(x),current=x.id===state.jobId;return `<article class="item-card"><h3>${x.title}<span class="meta">${money(x.pay)}/mo</span></h3><p>${x.path} · Level ${x.level}. ${current?'Your current role.':x.previous?'Next step in your path.':'Entry-level opportunity.'}</p><p class="meta">${req.length?`Needs: ${req.join(' · ')}`:'Requirements met'}</p><button data-job="${x.id}" ${current||req.length?'disabled':''}>${current?'Current job':req.length?'Locked':'Take this job'}</button></article>`}).join('');
  $('education-list').innerHTML=EDUCATION.map(x=>{const active=state.enrolledEducation===x.id,done=ed.id===x.id;return `<article class="item-card"><h3>${x.name}<span class="meta">${x.cost?money(x.cost):'Free'}</span></h3><p>${x.months?`${x.months} study months · `:''}${x.unlocks}.</p><button data-education="${x.id}" ${done||active||state.money<x.cost?'disabled':''}>${done?'Completed':active?`${state.educationProgress}/${x.months} months`:state.money<x.cost?'Need more money':'Enroll'}</button></article>`}).join('');
  $('skill-list').innerHTML=Object.entries(SKILLS).map(([id,name])=>`<div class="skill-row"><strong>${name}</strong><div class="progress"><i style="width:${state.skills[id]}%"></i></div><button class="secondary" data-train="${id}">Train $40</button></div>`).join('');
  $('housing-list').innerHTML=HOUSING.map(x=>`<article class="item-card"><h3>${x.name}<span class="meta">${x.cost?money(x.cost):'Free'}</span></h3><p>${money(x.expense)}/mo · +${x.happiness} Happiness · Status ${x.status}</p><button data-housing="${x.id}" ${x.id===state.housingId||state.money<x.cost?'disabled':''}>${x.id===state.housingId?'Current home':state.money<x.cost?'Save more':'Move here'}</button></article>`).join('');
  $('purchase-list').innerHTML=PURCHASES.map(x=>`<article class="item-card"><h3>${x.name}<span class="meta">${money(x.cost)}</span></h3><p>${x.description}</p><button data-purchase="${x.id}" ${state.purchases.includes(x.id)||state.money<x.cost?'disabled':''}>${state.purchases.includes(x.id)?'Owned':state.money<x.cost?'Save more':'Buy'}</button></article>`).join('');
  const stats=[['Money',money(state.money),'Cash on hand'],['Career',state.career,'Career momentum'],['Health',Math.round(state.health),'Wellbeing'],['Social',Math.round(state.social),'Community'],['Education',ed.name,'Highest completed'],['Experience',`${Math.floor(state.experience)} months`,'Work experience'],['Housing status',h.status,'Lifestyle'],['Purchases',state.purchases.length,'Useful things']];$('stats-list').innerHTML=stats.map(x=>`<div class="stat-card"><span>${x[0]}</span><strong>${x[1]}</strong><span>${x[2]}</span></div>`).join('');
  $('milestone-list').innerHTML=state.milestones.length?state.milestones.map(x=>`<div class="timeline-item"><strong>${x.title}</strong><span>Age ${Math.floor(x.age/12)}y ${x.age%12}m</span></div>`).join(''):'<p class="panel-copy">Your first job, home and big goals will appear here as you reach them.</p>';
}
function switchTab(tab){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active-panel',p.id===tab));}
document.addEventListener('click',e=>{const tab=e.target.closest('[data-tab]');if(tab)switchTab(tab.dataset.tab);const action=e.target.closest('[data-action]');if(action)doAction(action.dataset.action);const train=e.target.closest('[data-train]');if(train){actionDataSkill=train.dataset.train;doAction('train');actionDataSkill=null;}const jb=e.target.closest('[data-job]');if(jb&&!jb.disabled){state.jobId=jb.dataset.job;state.career+=JOBS.find(x=>x.id===state.jobId).level*4;log(`Started work as ${JOBS.find(x=>x.id===state.jobId).title}.`);checkMilestones();save();render();notify('New job started!');}const el=e.target.closest('[data-education]');if(el&&!el.disabled){const ed=EDUCATION.find(x=>x.id===el.dataset.education);if(ed.months===0){state.educationId=ed.id;}else{state.money-=ed.cost;state.enrolledEducation=ed.id;state.educationProgress=0;log(`Enrolled in ${ed.name}.`);}save();render();}const ho=e.target.closest('[data-housing]');if(ho&&!ho.disabled){const h=HOUSING.find(x=>x.id===ho.dataset.housing);state.money-=h.cost;state.housingId=h.id;state.happiness=clamp(state.happiness+h.happiness);log(`Moved into a ${h.name.toLowerCase()}.`);checkMilestones();save();render();notify('New home unlocked!');}const pu=e.target.closest('[data-purchase]');if(pu&&!pu.disabled){const p=PURCHASES.find(x=>x.id===pu.dataset.purchase);state.money-=p.cost;state.purchases.push(p.id);changeEffects(p.effect||{});log(`Bought ${p.name}.`);checkMilestones();save();render();notify(`${p.name} added to your life.`);}const ev=e.target.closest('[data-event-option]');if(ev&&pendingEvent){const option=pendingEvent.options[Number(ev.dataset.eventOption)];changeEffects(option.effects);log(`${pendingEvent.title} You chose: ${option.label}.`);pendingEvent=null;$('decision-modal').classList.add('hidden');checkMilestones();save();render();notify('Decision made.');}if(e.target.closest('[data-action="reset"]')){if(confirm('Start a completely new life? Your current save will be replaced.')){localStorage.removeItem('lifesim-save');state=loadState();render();notify('A new life begins.');}}});
render();
