/* Money Clicker is a local-only idle game. Accounts and saves never leave this device. */
const SAVE_KEY = 'money-clicker-save-v1';
const ACCOUNT_DB_NAME = 'money-clicker-local-accounts-v1';
const ACCOUNT_SESSION_KEY = 'money-clicker-active-account-v1';
const ACCOUNT_LIST_KEY = 'money-clicker-accounts-v1';
const ACCOUNT_SAVE_PREFIX = 'money-clicker-account-save-v1:';
const PBKDF2_ITERATIONS = 150000;
const SAVE_INTERVAL = 3000;
const OFFLINE_CAP = 12 * 60 * 60;
const GENERATORS = [
  {id:'auto-clicker',name:'Auto Clicker',icon:'⌁',baseCost:50,perSecond:1,milestones:[[10,2],[25,2],[50,3],[100,5]]},
  {id:'cash-register',name:'Cash Register',icon:'▣',baseCost:250,perSecond:5,milestones:[[10,2],[25,2],[50,3],[100,5]]},
  {id:'atm',name:'ATM',icon:'▤',baseCost:1000,perSecond:20,milestones:[[10,2],[25,2],[50,3],[100,5]]},
  {id:'money-printer',name:'Money Printer',icon:'▥',baseCost:5000,perSecond:100,milestones:[[10,2],[25,2],[50,3],[100,5]]},
  {id:'bank',name:'Bank',icon:'⌂',baseCost:25000,perSecond:500,milestones:[[10,2],[25,2],[50,3],[100,5]]},
  {id:'investment-firm',name:'Investment Firm',icon:'↗',baseCost:150000,perSecond:3000,milestones:[[10,2],[25,2],[50,3],[100,5]]},
  {id:'money-factory',name:'Money Factory',icon:'⚙',baseCost:1000000,perSecond:20000,milestones:[[10,2],[25,2],[50,3],[100,5]]},
  {id:'mega-corporation',name:'Mega Corporation',icon:'◆',baseCost:10000000,perSecond:250000,milestones:[[10,2],[25,2],[50,3],[100,5]]}
];
const CLICK_MILESTONES = [[10,2],[25,2],[50,3],[100,5]];
const CLICK_UPGRADES = [
  {id:'better-fingers',name:'Better Fingers',icon:'✋',description:'+1 money per click',baseCost:25,add:1},
  {id:'reinforced-mouse',name:'Reinforced Mouse',icon:'⌁',description:'+3 money per click',baseCost:100,add:3},
  {id:'golden-clicking',name:'Golden Clicking',icon:'✦',description:'+10 money per click',baseCost:500,add:10},
  {id:'power-clicks',name:'Power Clicks',icon:'ϟ',description:'+40 money per click',baseCost:2500,add:40},
  {id:'money-magnet',name:'Money Magnet',icon:'◈',description:'+150 money per click',baseCost:15000,add:150},
  {id:'diamond-hands',name:'Diamond Hands',icon:'◇',description:'+750 money per click',baseCost:100000,add:750},
  {id:'platinum-fingers',name:'Platinum Fingers',icon:'⬡',description:'+4,000 money per click',baseCost:750000,add:4000},
  {id:'quantum-mouse',name:'Quantum Mouse',icon:'◌',description:'+25,000 money per click',baseCost:5000000,add:25000},
  {id:'reality-clicker',name:'Reality Clicker',icon:'◉',description:'+175,000 money per click',baseCost:40000000,add:175000},
  {id:'cosmic-touch',name:'Cosmic Touch',icon:'✧',description:'+1,500,000 money per click',baseCost:350000000,add:1500000},
  {id:'billionaire-fingers',name:'Billionaire Fingers',icon:'♛',description:'+15,000,000 money per click',baseCost:3000000000,add:15000000},
  {id:'reality-breaker',name:'Reality Breaker',icon:'⟁',description:'+175,000,000 money per click',baseCost:30000000000,add:175000000},
  {id:'infinite-click',name:'Infinite Click',icon:'∞',description:'+2,500,000,000 money per click',baseCost:400000000000,add:2500000000}
];
CLICK_UPGRADES.forEach(upgrade=>{upgrade.milestones=CLICK_MILESTONES;});
const DEFAULT_STATE = {version:1,money:0,lifetime:0,clicks:0,clickEarned:0,passiveEarned:0,timePlayed:0,lastTick:Date.now(),lastSeen:Date.now(),clickUpgrades:{},generators:{},milestones:[],activity:[{time:Date.now(),text:'Your balance is $0. Click the coin to begin.'}]};
const readJson=(key,fallback)=>{try{const value=JSON.parse(localStorage.getItem(key));return value??fallback;}catch{return fallback;}};
const writeJson=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));}catch{}};
function normalizeUsername(value){return String(value||'').trim().toLocaleLowerCase();}
function encodeBytes(bytes){let text='';for(const byte of bytes)text+=String.fromCharCode(byte);return btoa(text);}
function decodeBytes(value){const text=atob(value);return Uint8Array.from(text,char=>char.charCodeAt(0));}
async function hashPassword(password,salt){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:PBKDF2_ITERATIONS,hash:'SHA-256'},key,256);return encodeBytes(new Uint8Array(bits));}
async function verifyPassword(password,account){const actual=decodeBytes(await hashPassword(password,decodeBytes(account.salt))),expected=decodeBytes(account.hash);if(actual.length!==expected.length)return false;let mismatch=0;for(let i=0;i<actual.length;i++)mismatch|=actual[i]^expected[i];return mismatch===0;}
function openAccountDatabase(){if(!('indexedDB' in window))return Promise.reject(new Error('IndexedDB unavailable'));return new Promise((resolve,reject)=>{const request=indexedDB.open(ACCOUNT_DB_NAME,1);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains('accounts'))db.createObjectStore('accounts',{keyPath:'id'});if(!db.objectStoreNames.contains('saves'))db.createObjectStore('saves',{keyPath:'accountId'});};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error||new Error('IndexedDB failed'));});}
function idbRequest(db,storeName,mode,operation){return new Promise((resolve,reject)=>{try{const tx=db.transaction(storeName,mode),request=operation(tx.objectStore(storeName));request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error||new Error('IndexedDB request failed'));tx.onerror=()=>reject(tx.error||new Error('IndexedDB transaction failed'));}catch(error){reject(error);}});}
function createAccountStore(){let dbPromise;const db=()=>dbPromise||(dbPromise=openAccountDatabase());const fallbackAccounts=()=>readJson(ACCOUNT_LIST_KEY,[]);const fallbackSave=id=>readJson(`${ACCOUNT_SAVE_PREFIX}${encodeURIComponent(id)}`,null);return {async listAccounts(){try{const records=await idbRequest(await db(),'accounts','readonly',store=>store.getAll());if(records.length)return records.sort((a,b)=>a.username.localeCompare(b.username));}catch{}return fallbackAccounts().sort((a,b)=>a.username.localeCompare(b.username));},async getAccount(id){try{const record=await idbRequest(await db(),'accounts','readonly',store=>store.get(id));if(record)return record;}catch{}return fallbackAccounts().find(account=>account.id===id)||null;},async saveAccount(account){const accounts=fallbackAccounts().filter(item=>item.id!==account.id);accounts.push(account);writeJson(ACCOUNT_LIST_KEY,accounts);try{await idbRequest(await db(),'accounts','readwrite',store=>store.put(account));}catch{}return account;},async getSave(id){try{const record=await idbRequest(await db(),'saves','readonly',store=>store.get(id));if(record&&record.data)return record.data;}catch{}return fallbackSave(id);},async saveSave(id,data){writeJson(`${ACCOUNT_SAVE_PREFIX}${encodeURIComponent(id)}`,data);try{await idbRequest(await db(),'saves','readwrite',store=>store.put({accountId:id,data}));}catch{}},async deleteAccount(id){const accounts=fallbackAccounts().filter(item=>item.id!==id);writeJson(ACCOUNT_LIST_KEY,accounts);try{const database=await db();await idbRequest(database,'accounts','readwrite',store=>store.delete(id));await idbRequest(database,'saves','readwrite',store=>store.delete(id));}catch{}try{localStorage.removeItem(`${ACCOUNT_SAVE_PREFIX}${encodeURIComponent(id)}`);}catch{}}};}
const accountStore=createAccountStore();
let state=freshState(); let currentAccount=null; let saveQueue=Promise.resolve(); let selectedAmount=1; let toastTimer; let lastAutoSave=Date.now();
const $=id=>document.getElementById(id); const fmt=n=>formatNumber(n); const compact=n=>formatNumber(n);
function freshState(){const now=Date.now();return {...structuredClone(DEFAULT_STATE),lastTick:now,lastSeen:now,activity:[{time:now,text:'Your balance is $0. Click the coin to begin.'}]};}
function loadState(saved){if(!saved||typeof saved!=='object')return freshState();const clickUpgrades={...(saved.clickUpgrades||{})},generators={...(saved.generators||{})};for(const x of CLICK_UPGRADES)clickUpgrades[x.id]=Number(clickUpgrades[x.id]||0);for(const x of GENERATORS)generators[x.id]=Number(generators[x.id]||0);return {...freshState(),...saved,clickUpgrades,generators,milestones:Array.isArray(saved.milestones)?saved.milestones:[],activity:Array.isArray(saved.activity)&&saved.activity.length?saved.activity:freshState().activity};}
function formatNumber(value){if(!Number.isFinite(value))return '∞';const n=Math.max(0,value),units=['','K','M','B','T','Qa','Qi','Sx','Sp','Oc','No','Dc'];let unit=0,v=n;while(v>=1000&&unit<units.length-1){v/=1000;unit++;}if(unit===0)return `$${Math.floor(v).toLocaleString()}`;const digits=v>=100?0:v>=10?1:2;return `$${v.toFixed(digits).replace(/\.0+$|(?<=\.[0-9])0+$/,'')}${units[unit]}`;}
function plainNumber(value){if(!Number.isFinite(value))return '∞';return formatNumber(value).replace('$','');}
function costFor(base,owned,amount=1){if(amount<=0)return 0;const scale=1.15;return base*Math.pow(scale,owned)*(Math.pow(scale,amount)-1)/(scale-1);}
function upgradeCost(upgrade){return Math.ceil(upgrade.baseCost*Math.pow(1.15,state.clickUpgrades[upgrade.id]||0));}
function generatorMultiplier(generator){const owned=state.generators[generator.id]||0;return generator.milestones.reduce((mult,[needed,bonus])=>owned>=needed?mult*bonus:mult,1);}
function generatorRate(generator){return generator.perSecond*generatorMultiplier(generator)*(state.generators[generator.id]||0);}
function perSecond(){return GENERATORS.reduce((sum,g)=>sum+generatorRate(g),0);}
function clickUpgradeMultiplier(upgrade){const owned=state.clickUpgrades[upgrade.id]||0;return upgrade.milestones.reduce((mult,[needed,bonus])=>owned>=needed?mult*bonus:mult,1);}
function rarityClass(mult){if(mult>=60)return 'rarity-max';if(mult>=12)return 'rarity-epic';if(mult>=4)return 'rarity-rare';if(mult>=2)return 'rarity-uncommon';return '';}
function clickPower(){return 1+CLICK_UPGRADES.reduce((sum,u)=>sum+(state.clickUpgrades[u.id]||0)*u.add*clickUpgradeMultiplier(u),0);}
function totalGenerators(){return GENERATORS.reduce((sum,g)=>sum+(state.generators[g.id]||0),0);}
function totalUpgrades(){return CLICK_UPGRADES.reduce((sum,u)=>sum+(state.clickUpgrades[u.id]||0),0);}
function persist(){if(!currentAccount)return saveQueue;const accountId=currentAccount.id,snapshot=structuredClone(state);lastAutoSave=Date.now();$('save-state').textContent='Saving…';saveQueue=saveQueue.catch(()=>{}).then(()=>accountStore.saveSave(accountId,snapshot)).then(()=>{if(currentAccount&&currentAccount.id===accountId)$('save-state').textContent='Saved locally';});return saveQueue;}
function save(){if(!currentAccount)return Promise.resolve();state.lastSeen=Date.now();return persist();}
function log(text){state.activity.unshift({time:Date.now(),text});state.activity=state.activity.slice(0,15);}
function addMoney(amount,kind){if(amount<=0)return;state.money+=amount;state.lifetime+=amount;if(kind==='click'){state.clicks++;state.clickEarned+=amount;}else state.passiveEarned+=amount;}
function applyPassive(seconds){const earned=perSecond()*seconds;if(earned>0)addMoney(earned,'passive');return earned;}
function formatDuration(seconds){const s=Math.max(0,Math.floor(seconds));const h=Math.floor(s/3600),m=Math.floor((s%3600)/60),sec=s%60;if(h)return `${h} hour${h===1?'':'s'} ${m} minute${m===1?'':'s'}`;if(m)return `${m} minute${m===1?'':'s'} ${sec} second${sec===1?'':'s'}`;return `${sec} second${sec===1?'':'s'}`;}
function catchUp(){const now=Date.now(),elapsed=Math.max(0,(now-(state.lastSeen||now))/1000),capped=Math.min(elapsed,OFFLINE_CAP),earned=applyPassive(capped);state.timePlayed+=capped;state.lastTick=now;state.lastSeen=now;if(earned>0&&elapsed>15){$('offline-duration').textContent=`You were away for ${formatDuration(Math.min(elapsed,OFFLINE_CAP))}.`;$('offline-money').textContent=fmt(earned);$('offline-modal').classList.remove('hidden');log(`Businesses earned ${fmt(earned)} while you were away.`);}save();}
function renderResources(){const rate=perSecond(),power=clickPower(),selection=selectedAmount==='max'?'MAX':`×${selectedAmount}`;$('money').textContent=fmt(state.money);$('per-click').textContent=fmt(power);$('per-second').textContent=fmt(rate);$('mobile-money').textContent=fmt(state.money);$('mobile-per-click').textContent=fmt(power);$('mobile-per-second').textContent=fmt(rate);$('status-line').textContent=rate?`Your money is working at ${fmt(rate)} / sec`:'Click the coin to start your fortune';$('upgrade-count').textContent=`${totalUpgrades()} bought`;$('generator-count').textContent=`${totalGenerators()} owned`;$('selected-amount-label').textContent=`${selection} selected`;}
function render(){renderResources();renderUpgrades();renderGenerators();renderStats();}
function renderUpgrades(){$('upgrade-list').innerHTML=CLICK_UPGRADES.map(upgrade=>{const owned=state.clickUpgrades[upgrade.id]||0,amount=upgradeAmount(upgrade),cost=amount?costFor(upgrade.baseCost,owned,amount):0,can=amount>0&&state.money>=cost,mult=clickUpgradeMultiplier(upgrade),perCopy=upgrade.add*mult,next=upgrade.milestones.find(([needed])=>owned<needed),milestones=upgrade.milestones.map(([needed,bonus])=>`<span class="milestone ${owned>=needed?'unlocked':''}">${needed}: ×${bonus}</span>`).join('');return `<article class="upgrade-card ${rarityClass(mult)} ${can?'can-buy':''}"><div class="card-row"><div class="card-title"><i class="card-icon">${upgrade.icon}</i><div><strong>${upgrade.name}</strong><span>${upgrade.description} · ${owned} owned</span></div></div><span class="card-price ${can?'':'dim'}">${amount?fmt(cost):'—'}</span></div><p class="generator-copy">+${plainNumber(perCopy)}/click each · ${fmt(owned*perCopy)}/click total</p><p class="generator-total">${next?`Next boost at ${next[0]} owned (×${next[1]})`: 'All milestones unlocked'}</p><div class="milestone-row">${milestones}</div><button class="buy-button" data-upgrade="${upgrade.id}" ${can?'':'disabled'}>${amount?`Buy ×${amount===1?'1':amount}`:'Cannot afford'}</button></article>`;}).join('');}
function maxAffordableFor(base,owned){if(state.money<base*Math.pow(1.15,owned))return 0;let low=1,high=1;while(costFor(base,owned,high)<=state.money&&high<1e9)high*=2;while(low<high){const mid=Math.ceil((low+high)/2);if(costFor(base,owned,mid)<=state.money)low=mid;else high=mid-1;}return low;}
function maxAffordable(generator){return maxAffordableFor(generator.baseCost,state.generators[generator.id]||0);}
function upgradeAmount(upgrade){return selectedAmount==='max'?maxAffordableFor(upgrade.baseCost,state.clickUpgrades[upgrade.id]||0):selectedAmount;}
function purchaseAmount(generator){return selectedAmount==='max'?maxAffordable(generator):selectedAmount;}
function renderGenerators(){$('generator-list').innerHTML=GENERATORS.map(generator=>{const owned=state.generators[generator.id]||0,amount=purchaseAmount(generator),cost=amount?costFor(generator.baseCost,owned,amount):0,can=amount>0&&state.money>=cost,mult=generatorMultiplier(generator),rate=generatorRate(generator),next=generator.milestones.find(([needed])=>owned<needed),milestones=generator.milestones.map(([needed,bonus])=>`<span class="milestone ${owned>=needed?'unlocked':''}">${needed}: ×${bonus}</span>`).join('');return `<article class="generator-card ${rarityClass(mult)} ${can?'can-buy':''}"><div class="card-row"><div class="card-title"><i class="card-icon generator-icon">${generator.icon}</i><div><strong>${generator.name}</strong><span>Owned: ${owned}</span></div></div><span class="card-price ${can?'':'dim'}">${amount?fmt(cost):'—'}</span></div><p class="generator-copy">+${plainNumber(generator.perSecond*mult)}/sec each · ${fmt(rate)}/sec total</p><p class="generator-total">${next?`Next boost at ${next[0]} owned (×${next[1]})`: 'All milestones unlocked'}</p><div class="milestone-row">${milestones}</div><button class="buy-button ${can?'':'secondary'}" data-generator="${generator.id}" ${can?'':'disabled'}>${amount?`Buy ×${amount===1?'1':amount} · ${fmt(cost)}`:'Cannot afford'}</button></article>`;}).join('');}
function refreshPurchaseStates(){document.querySelectorAll('[data-upgrade]').forEach(button=>{const upgrade=CLICK_UPGRADES.find(item=>item.id===button.dataset.upgrade),owned=state.clickUpgrades[upgrade.id]||0,amount=upgradeAmount(upgrade),cost=amount?costFor(upgrade.baseCost,owned,amount):0,can=amount>0&&state.money>=cost,card=button.closest('.upgrade-card');card.classList.toggle('can-buy',can);button.disabled=!can;button.textContent=amount?`Buy ×${amount===1?'1':amount}`:'Cannot afford';card.querySelector('.card-price').textContent=amount?fmt(cost):'—';card.querySelector('.card-price').classList.toggle('dim',!can);});document.querySelectorAll('[data-generator]').forEach(button=>{const generator=GENERATORS.find(item=>item.id===button.dataset.generator),amount=purchaseAmount(generator),cost=amount?costFor(generator.baseCost,state.generators[generator.id]||0,amount):0,can=amount>0&&state.money>=cost,card=button.closest('.generator-card');card.classList.toggle('can-buy',can);button.disabled=!can;button.textContent=amount?`Buy ×${amount===1?'1':amount} · ${fmt(cost)}`:'Cannot afford';button.classList.toggle('secondary',!can);card.querySelector('.card-price').textContent=amount?fmt(cost):'—';card.querySelector('.card-price').classList.toggle('dim',!can);});}
function renderStats(){const stats=[['Current money',fmt(state.money)],['Lifetime money',fmt(state.lifetime)],['Manual clicks',state.clicks.toLocaleString()],['Money from clicks',fmt(state.clickEarned)],['Passive money',fmt(state.passiveEarned)],['Money per click',fmt(clickPower())],['Money per second',fmt(perSecond())],['Generators owned',totalGenerators().toLocaleString()],['Upgrades purchased',totalUpgrades().toLocaleString()],['Time played',formatDuration(state.timePlayed)]];$('stats-grid').innerHTML=stats.map(([label,value])=>`<div class="stat"><span>${label}</span><strong>${value}</strong></div>`).join('');}
function notify(text){const node=$('toast');node.textContent=text;node.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>node.classList.remove('show'),2400);}
function setMobileView(view){document.body.dataset.mobileView=view;document.querySelectorAll('.game-view-button').forEach(button=>{const active=button.dataset.mobileView===view;button.classList.toggle('active',active);button.setAttribute('aria-current',active?'page':'false');});if(view==='stats')$('stats-panel').classList.remove('hidden');else $('stats-panel').classList.add('hidden');}
function burst(x,y){const stage=$('particles');for(let i=0;i<8;i++){const p=document.createElement('i');p.className='particle';p.style.left=`${x}px`;p.style.top=`${y}px`;p.style.setProperty('--x',`${Math.cos(i/8*Math.PI*2)*55}px`);p.style.setProperty('--y',`${Math.sin(i/8*Math.PI*2)*55}px`);stage.appendChild(p);setTimeout(()=>p.remove(),600);}}
function floatMoney(event,amount){const text=document.createElement('span');text.className='float-money';text.textContent=`+${fmt(amount)}`;text.style.left=`${event.clientX-18}px`;text.style.top=`${event.clientY-12}px`;document.body.appendChild(text);setTimeout(()=>text.remove(),850);}
function clickMoney(event){const amount=clickPower();addMoney(amount,'click');state.timePlayed+=0;const orb=$('money-orb');orb.classList.remove('bounce');void orb.offsetWidth;orb.classList.add('bounce');setTimeout(()=>orb.classList.remove('bounce'),140);floatMoney(event,amount);burst(event.clientX,event.clientY);renderResources();refreshPurchaseStates();renderStats();}
function checkClickMilestones(upgrade,before,after){for(const [needed,bonus] of upgrade.milestones){const key=`click-${upgrade.id}-${needed}`;if(before<needed&&after>=needed&&!state.milestones.includes(key)){state.milestones.push(key);log(`${upgrade.name} milestone: ${needed} owned. Click power multiplied ×${bonus}.`);notify(`${upgrade.name.toUpperCase()} MILESTONE! ${needed} owned · click power ×${bonus}`);}}}
function buyUpgrade(id){const upgrade=CLICK_UPGRADES.find(item=>item.id===id),amount=upgradeAmount(upgrade),owned=state.clickUpgrades[id]||0,cost=amount?costFor(upgrade.baseCost,owned,amount):0;if(!amount||state.money<cost)return;state.money-=cost;state.clickUpgrades[id]=owned+amount;checkClickMilestones(upgrade,owned,state.clickUpgrades[id]);log(`Bought ${amount} ${upgrade.name}${amount===1?'':' upgrades'}. Clicks are now worth ${fmt(clickPower())}.`);save();render();notify(`${upgrade.name} ×${amount} purchased`);}
function checkMilestones(generator,before,after){for(const [needed,bonus] of generator.milestones){const key=`${generator.id}-${needed}`;if(before<needed&&after>=needed&&!state.milestones.includes(key)){state.milestones.push(key);log(`${generator.name} milestone: ${needed} owned. Production multiplied ×${bonus}.`);notify(`${generator.name.toUpperCase()} MILESTONE! ${needed} owned · production ×${bonus}`);}}}
function buyGenerator(id){const generator=GENERATORS.find(item=>item.id===id),amount=purchaseAmount(generator),cost=amount?costFor(generator.baseCost,state.generators[id]||0,amount):0;if(!amount||state.money<cost)return;const before=state.generators[id]||0;state.money-=cost;state.generators[id]=before+amount;checkMilestones(generator,before,state.generators[id]);log(`Bought ${amount} ${generator.name}${amount===1?'':'s'}.`);save();render();notify(`${generator.name} added`);}
function exportSave(){save();const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='money-clicker-save.json';link.click();URL.revokeObjectURL(url);notify('Save exported');}
function importSave(file){const reader=new FileReader();reader.onload=()=>{try{const incoming=JSON.parse(reader.result);if(typeof incoming.money!=='number'||!incoming.generators||!incoming.clickUpgrades)throw Error('invalid');state=loadState(incoming);save();render();notify('Save imported');}catch{notify('That save file is not valid.');}};reader.readAsText(file);}
function reset(){if(!confirm('Reset all Money Clicker progress for this account? This cannot be undone.'))return;state=freshState();save();render();notify('Fresh start: $0.');}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));}
function setAuthError(message=''){ $('auth-error').textContent=message; }
function setAuthView(view){const create=view==='create';$('login-form').classList.toggle('hidden',create);$('create-form').classList.toggle('hidden',!create);document.querySelectorAll('[data-auth-view]').forEach(tab=>{const active=tab.dataset.authView===view;tab.classList.toggle('active',active);tab.setAttribute('aria-selected',String(active));});setAuthError('');}
function readSession(){return readJson(ACCOUNT_SESSION_KEY,null);}
function writeSession(account){writeJson(ACCOUNT_SESSION_KEY,{id:account.id});}
function clearSession(){try{localStorage.removeItem(ACCOUNT_SESSION_KEY);}catch{}}
function setAccountIndicator(){const name=currentAccount?currentAccount.username:'';$('account-name').textContent=name;$('mobile-account-name').textContent=name?`👤 ${name}`:'';}
function hasLegacySave(){return Boolean(readJson(SAVE_KEY,null));}
async function renderAccounts(){const accounts=await accountStore.listAccounts();$('account-list').innerHTML=accounts.length?accounts.map(account=>`<div class="account-row"><strong>${escapeHtml(account.username)}</strong><button class="account-use" type="button" data-account-select="${escapeHtml(account.id)}" data-account-username="${escapeHtml(account.username)}">Use account</button></div>`).join(''):'<p class="account-empty">No local accounts yet.</p>';$('legacy-migration').classList.toggle('hidden',accounts.length>0||!hasLegacySave());}
function showAuth(){currentAccount=null;state=freshState();selectedAmount=1;lastAutoSave=Date.now();clearSession();setAccountIndicator();document.body.classList.add('auth-locked');$('auth-screen').classList.remove('hidden');setAuthView('login');renderAccounts();}
async function enterAccount(account,options={}){const saved=await accountStore.getSave(account.id);currentAccount=account;state=loadState(saved);if(!saved&&options.migrateLegacy){const legacy=readJson(SAVE_KEY,null);if(legacy){state=loadState(legacy);await accountStore.saveSave(account.id,state);try{localStorage.removeItem(SAVE_KEY);}catch{}}}writeSession(account);setAccountIndicator();document.body.classList.remove('auth-locked');$('auth-screen').classList.add('hidden');$('login-password').value='';$('create-password').value='';$('create-confirm').value='';catchUp();render();}
async function loginAccount(){const username=normalizeUsername($('login-username').value),password=$('login-password').value;if(!username||!password){setAuthError('Enter your username and password.');return;}const account=await accountStore.getAccount(username);if(!account||!(await verifyPassword(password,account))){setAuthError('Incorrect username or password.');return;}await enterAccount(account);}
async function createAccount(){const displayName=$('create-username').value.trim(),username=normalizeUsername(displayName),password=$('create-password').value,confirmPassword=$('create-confirm').value;if(!username){setAuthError('Username cannot be blank.');return;}if(!password){setAuthError('Password cannot be blank.');return;}if(password!==confirmPassword){setAuthError('Passwords do not match.');return;}if(await accountStore.getAccount(username)){setAuthError('That username already exists on this device.');return;}const salt=new Uint8Array(16);crypto.getRandomValues(salt);const account={id:username,username:displayName,salt:encodeBytes(salt),hash:await hashPassword(password,salt),createdAt:Date.now()};const accounts=await accountStore.listAccounts();const migrate=accounts.length===0&&$('migrate-save').checked&&hasLegacySave();await accountStore.saveAccount(account);await enterAccount(account,{migrateLegacy:migrate});}
async function deleteAccount(){const username=normalizeUsername($('delete-username').value),password=$('delete-password').value;if(!username||!password){setAuthError('Enter the account username and password to delete it.');return;}const account=await accountStore.getAccount(username);if(!account||!(await verifyPassword(password,account))){setAuthError('Incorrect username or password.');return;}if(!confirm(`Permanently delete ${account.username} and all of its Coin Clicker progress?`))return;await accountStore.deleteAccount(account.id);if(readSession()?.id===account.id)clearSession();$('delete-username').value='';$('delete-password').value='';setAuthError('Account deleted.');await renderAccounts();}
async function logout(){if(!currentAccount)return;const leaving=currentAccount;await save();if(!currentAccount||currentAccount.id!==leaving.id)return;showAuth();$('login-username').value=leaving.username;$('delete-username').value=leaving.username;await renderAccounts();notify('Logged out');}
async function bootAccounts(){setAccountIndicator();await renderAccounts();const session=readSession();if(session?.id){const account=await accountStore.getAccount(session.id);if(account){await enterAccount(account);return;}}showAuth();}
document.addEventListener('click',event=>{const orb=event.target.closest('#money-orb');if(orb)clickMoney(event);const mobileTab=event.target.closest('.game-view-button[data-mobile-view]');if(mobileTab){setMobileView(mobileTab.dataset.mobileView);return;}const amount=event.target.closest('.amount-button');if(amount){event.preventDefault();selectedAmount=amount.dataset.amount==='max'?'max':Number(amount.dataset.amount);document.querySelectorAll('.amount-button').forEach(button=>{const active=button===amount;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active));});render();}const upgrade=event.target.closest('[data-upgrade]');if(upgrade)buyUpgrade(upgrade.dataset.upgrade);const generator=event.target.closest('[data-generator]');if(generator)buyGenerator(generator.dataset.generator);const action=event.target.closest('[data-action]');if(!action)return;if(action.dataset.action==='save'){save();notify('Game saved');}if(action.dataset.action==='export')exportSave();if(action.dataset.action==='import')$('import-file').click();if(action.dataset.action==='reset')reset();if(action.dataset.action==='stats'){const open=$('stats-panel').classList.toggle('hidden');setMobileView(open?'stats':'play');}if(action.dataset.action==='logout')logout();if(action.dataset.action==='close-offline')$('offline-modal').classList.add('hidden');});
document.addEventListener('click',event=>{const authTab=event.target.closest('[data-auth-view]');if(authTab){setAuthView(authTab.dataset.authView);return;}const selected=event.target.closest('[data-account-select]');if(selected){$('login-username').value=selected.dataset.accountUsername;$('delete-username').value=selected.dataset.accountUsername;setAuthView('login');$('login-password').focus();}});
$('login-form').addEventListener('submit',event=>{event.preventDefault();loginAccount().catch(()=>setAuthError('Unable to access local accounts right now.'));});
$('create-form').addEventListener('submit',event=>{event.preventDefault();createAccount().catch(()=>setAuthError('Unable to create a local account right now.'));});
$('delete-form').addEventListener('submit',event=>{event.preventDefault();deleteAccount().catch(()=>setAuthError('Unable to delete that local account right now.'));});
$('refresh-accounts').addEventListener('click',()=>renderAccounts().catch(()=>setAuthError('Unable to read local accounts right now.')));
$('import-file').addEventListener('change',event=>{if(event.target.files[0])importSave(event.target.files[0]);event.target.value='';});
window.addEventListener('beforeunload',save);document.addEventListener('visibilitychange',()=>{if(document.hidden)persist();else{catchUp();render();}});
if(window.matchMedia('(max-width:650px)').matches){const cancelGesture=event=>event.preventDefault();['gesturestart','gesturechange','gestureend'].forEach(type=>document.addEventListener(type,cancelGesture,{passive:false}));document.addEventListener('touchmove',event=>{if(event.touches.length>1)event.preventDefault();},{passive:false});}
bootAccounts().catch(()=>showAuth());
setInterval(()=>{if(document.hidden||!currentAccount)return;const now=Date.now(),seconds=Math.min(1,(now-state.lastTick)/1000);if(seconds<=0)return;state.lastTick=now;state.timePlayed+=seconds;applyPassive(seconds);if(now-lastAutoSave>=SAVE_INTERVAL)save();renderResources();refreshPurchaseStates();renderStats();},100);
